version: '3.8'

services:
  web:
    # 1. اسم الـ Image اللي بتتبني وبنرفعها
    image: 01013576608/odoo-custom:latest
    
    # 2. بنقول لدوكر يبنيها محلياً من الـ Dockerfile اللي في نفس المجلد
    build:
      context: .
      dockerfile: Dockerfile
      
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./custom_addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo_password

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo_password
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-web-data:
  odoo-db-data:

networks:
  default:
    name: odoo-network