name: Odoo DevOps CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-yaml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check if docker-compose exists
      run: |
        if [ ! -f docker-compose.yml ]; then
          echo "docker-compose.yml not found!"
          exit 1
        fi
        echo "File exists, structure check passed."